### ISSUE TITLE
Styling doesn't work on Windows

### ISSUE THREAD

**Issue by kristofzerbe** [catapart/magnitce-browser-mockup#3]
As good as the demo looked under Chrome/Android ... styling doesn't seems to work under Chrome/Firefox/i.e. under Windows:

![image](https://github.com/user-attachments/assets/edefc7bd-7cb7-48b3-b3ce-8c1325d84dda)

**Comment by catapart** [comment]
Unable to reproduce.
Any additional information you can provide about the context of your use-case would help me resolve the issues.

Here is the current demo page running in Chrome, Firefox, and Safari, each on Windows 10 (11 was tested as well).
![image](https://github.com/user-attachments/assets/477f9478-5d46-4db2-8480-caa80528242f)

**Comment by kristofzerbe** [comment]
There is no context at all. I was just curious about your project and opened up the demo page on my business laptop under Chrome/Edge 123 and Firefox 115.9.1esr. I guess it has something to do with the versions, because it looks nice on my private Chrome 128/129. Are you using some features which were introduced in these browsers at a certain version during the last year?

**Comment by catapart** [comment]
That's it then; non-current browser versions aren't being supported due to the library's use of nested CSS, which was only supported since June of this year (2024), in the latest cases. 

Next build should remove nested CSS to widen the supported browsers.

Thanks for the report!
